database:
  hostname: "{{ .Release.Name }}-postgres-headless"
environment:
  hostname: "{{ Release.Namespace }}.plaidcloud.io"
  designation: dev
  tempdir: ""
  verify_ssl: false
features:
  async_copy: true
  backward_compatible_state: true
  decrypted_accounts: true
  enable_cors: false
  fast_clean_csv: true
  flashback: true
  google_login: true
  table_update_recreate: true
  use_numeric_cast: true
rabbitmq:
  hostname: {{ .Release.Name }}-rabbitmq
  port: 5379
  username: plaidcloud
  password: some arbitrary password
  vhost: plaidcloud
  eventUsername: plaidcloud-events
  eventPassword: another arbitrary password
  eventVhost: plaidcloud-events
redisClient:
  timeout: 1
services:
  auth: http://{{ .Release.Name }}-auth
  client: http://{{ .Release.Name }}-client
  cron: http://{{ .Release.Name }}-cron
  data_explorer: http://{{ .Release.Name }}-data-explorer
  docs: http://{{ .Release.Name }}-docs
  flashback: http://{{ .Release.Name }}-flashback/rpc
  monitor: http://{{ .Release.Name }}-monitor
  plaidxl: http://{{ .Release.Name }}-plaidxl
  rpc: http://{{ .Release.Name }}-rpc/json_rpc
  superset: http://{{ .Release.Name }}-superset
  workflow: http://{{ .Release.Name }}-workflow
